const GET_HABILITATIONS_REQUEST = 'GET_HABILITATIONS_REQUEST';
const GET_HABILITATIONS_REQUEST_SUCCESS = 'GET_HABILITATIONS_REQUEST_SUCCESS';
const GET_HABILITATIONS_REQUEST_FAIL = 'GET_HABILITATIONS_REQUEST_FAIL';

const HabilitationsActions = {
  GET_HABILITATIONS_REQUEST,
  GET_HABILITATIONS_REQUEST_SUCCESS,
  GET_HABILITATIONS_REQUEST_FAIL,
};

export default HabilitationsActions;
