const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
const ARTICLE_LIST_REQUEST_SUCCES = 'ARTICLE_LIST_REQUEST_SUCCES';
const ARTICLE_LIST_REQUEST_FAIL = 'ARTICLE_LIST_REQUEST_FAIL';

const ArticlesActions = {
  ARTICLE_LIST_REQUEST,
  ARTICLE_LIST_REQUEST_FAIL,
  ARTICLE_LIST_REQUEST_SUCCES,
};

export default ArticlesActions;
